pipeline{

	agent {label 'linux'}

	environment {
		DOCKERHUB_CREDENTIALS=credentials('dockerhub')
	}

	stages {
	    
	    stage('gitclone') {

			steps {
				git 'https://github.com/divye1996/robot-shop.git'
			}
		}

		stage('Build') {

			steps {
				sh '''
        docker build --network=host -t divye1996/robot-shop:latest -f web/Dockerfile .
        '''
			}
		}

		stage('Login') {

			steps {
				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
			}
		}

		stage('Push') {

			steps {
				sh 'docker push divye1996/robot-shop:latest'
			}
		}
	}

	post {
		always {
			sh 'docker logout'
		}
	}

}
