pipeline {
  agent none

  stages {
    
    stage('Build') {
      
      steps {
        echo "Building robot-shop"
      }
    }
    
    stage('Test') {
      
      steps {
        echo "Testing robot-shop"
      }
    }
    
  }
}
